/*
Copyright (c) 2024 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "Base.hxx"

typedef struct DirectSound3DBufferQueryInterfaceMethodValue
{
    GUID ID;
    LPVOID* Object;
} DIRECTSOUND3DBUFFERQUERYINTERFACEMETHODVALUE, * LPDIRECTSOUND3DBUFFERQUERYINTERFACEMETHODVALUE;

typedef struct DirectSound3DBufferAddRefMethodValue
{

} DIRECTSOUND3DBUFFERADDREFMETHODVALUE, * LPDIRECTSOUND3DBUFFERADDREFMETHODVALUE;

typedef struct DirectSound3DBufferReleaseMethodValue
{

} DIRECTSOUND3DBUFFERRELEASEMETHODVALUE, * LPDIRECTSOUND3DBUFFERRELEASEMETHODVALUE;

typedef struct DirectSound3DBufferGetAllParametersMethodValue
{
    LPDS3DBUFFER Descriptor;
} DIRECTSOUND3DBUFFERGETALLPARAMETERSMETHODVALUE, * LPDIRECTSOUND3DBUFFERGETALLPARAMETERSMETHODVALUE;

typedef struct DirectSound3DBufferGetConeAnglesMethodValue
{
    LPDWORD InsideConeAngle;
    LPDWORD OutsideConeAngle;
} DIRECTSOUND3DBUFFERGETCONEANGLESMETHODVALUE, * LPDIRECTSOUND3DBUFFERGETCONEANGLESMETHODVALUE;

typedef struct DirectSound3DBufferGetConeOrientationMethodValue
{
    LPD3DVECTOR Orientation;
} DIRECTSOUND3DBUFFERGETCONEORIENTATIONMETHODVALUE, * LPDIRECTSOUND3DBUFFERGETCONEORIENTATIONMETHODVALUE;

typedef struct DirectSound3DBufferGetConeOutsideVolumeMethodValue
{
    LPLONG Volume;
} DIRECTSOUND3DBUFFERGETCONEOUTSIDEVOLUMEMETHODVALUE, * LPDIRECTSOUND3DBUFFERGETCONEOUTSIDEVOLUMEMETHODVALUE;

typedef struct DirectSound3DBufferGetMaxDistanceMethodValue
{
    LPD3DVALUE Distance;
} DIRECTSOUND3DBUFFERGETMAXDISTANCEMETHODVALUE, * LPDIRECTSOUND3DBUFFERGETMAXDISTANCEMETHODVALUE;

typedef struct DirectSound3DBufferGetMinDistanceMethodValue
{
    LPD3DVALUE Distance;
} DIRECTSOUND3DBUFFERGETMINDISTANCEMETHODVALUE, * LPDIRECTSOUND3DBUFFERGETMINDISTANCEMETHODVALUE;

typedef struct DirectSound3DBufferGetModeMethodValue
{
    LPDWORD Mode;
} DIRECTSOUND3DBUFFERGETMODEMETHODVALUE, * LPDIRECTSOUND3DBUFFERGETMODEMETHODVALUE;

typedef struct DirectSound3DBufferGetPositionMethodValue
{
    LPD3DVECTOR Position;
} DIRECTSOUND3DBUFFERGETPOSITIONMETHODVALUE, * LPDIRECTSOUND3DBUFFERGETPOSITIONMETHODVALUE;

typedef struct DirectSound3DBufferGetVelocityMethodValue
{
    LPD3DVECTOR Velocity;
} DIRECTSOUND3DBUFFERGETVELOCITYMETHODVALUE, * LPDIRECTSOUND3DBUFFERGETVELOCITYMETHODVALUE;

typedef struct DirectSound3DBufferSetAllParametersMethodValue
{
    LPCDS3DBUFFER Descriptor;
    DWORD Options;
} DIRECTSOUND3DBUFFERSETALLPARAMETERSMETHODVALUE, * LPDIRECTSOUND3DBUFFERSETALLPARAMETERSMETHODVALUE;

typedef struct DirectSound3DBufferSetConeAnglesMethodValue
{
    DWORD InsideConeAngle;
    DWORD OutsideConeAngle;
    DWORD Options;
} DIRECTSOUND3DBUFFERSETCONEANGLESMETHODVALUE, * LPDIRECTSOUND3DBUFFERSETCONEANGLESMETHODVALUE;

typedef struct DirectSound3DBufferSetConeOrientationMethodValue
{
    D3DVALUE X;
    D3DVALUE Y;
    D3DVALUE Z;
    DWORD Options;
} DIRECTSOUND3DBUFFERSETCONEORIENTATIONMETHODVALUE, * LPDIRECTSOUND3DBUFFERSETCONEORIENTATIONMETHODVALUE;

typedef struct DirectSound3DBufferSetConeOutsideVolumeMethodValue
{
    LONG Volume;
    DWORD Options;
} DIRECTSOUND3DBUFFERSETCONEOUTSIDEVOLUMEMETHODVALUE, * LPDIRECTSOUND3DBUFFERSETCONEOUTSIDEVOLUMEMETHODVALUE;

typedef struct DirectSound3DBufferSetMaxDistanceMethodValue
{
    D3DVALUE Distance;
    DWORD Options;
} DIRECTSOUND3DBUFFERSETMAXDISTANCEMETHODVALUE, * LPDIRECTSOUND3DBUFFERSETMAXDISTANCEMETHODVALUE;

typedef struct DirectSound3DBufferSetMinDistanceMethodValue
{
    D3DVALUE Distance;
    DWORD Options;
} DIRECTSOUND3DBUFFERSETMINDISTANCEMETHODVALUE, * LPDIRECTSOUND3DBUFFERSETMINDISTANCEMETHODVALUE;

typedef struct DirectSound3DBufferSetModeMethodValue
{
    DWORD Mode;
    DWORD Options;
} DIRECTSOUND3DBUFFERSETMODEMETHODVALUE, * LPDIRECTSOUND3DBUFFERSETMODEMETHODVALUE;

typedef struct DirectSound3DBufferSetPositionMethodValue
{
    D3DVALUE X;
    D3DVALUE Y;
    D3DVALUE Z;
    DWORD Options;
} DIRECTSOUND3DBUFFERSETPOSITIONMETHODVALUE, * LPDIRECTSOUND3DBUFFERSETPOSITIONMETHODVALUE;

typedef struct DirectSound3DBufferSetVelocityMethodValue
{
    D3DVALUE X;
    D3DVALUE Y;
    D3DVALUE Z;
    DWORD Options;
} DIRECTSOUND3DBUFFERSETVELOCITYMETHODVALUE, * LPDIRECTSOUND3DBUFFERSETVELOCITYMETHODVALUE;