/*
Copyright (c) 2024 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "Base.hxx"

typedef struct DirectSound3DListenerQueryInterfaceMethodValue
{
    GUID ID;
    LPVOID* Object;
} DIRECTSOUND3DLISTENERQUERYINTERFACEMETHODVALUE, * LPDIRECTSOUND3DLISTENERQUERYINTERFACEMETHODVALUE;

typedef struct DirectSound3DListenerAddRefMethodValue
{

} DIRECTSOUND3DLISTENERADDREFMETHODVALUE, * LPDIRECTSOUND3DLISTENERADDREFMETHODVALUE;

typedef struct DirectSound3DListenerReleaseMethodValue
{

} DIRECTSOUND3DLISTENERRELEASEMETHODVALUE, * LPDIRECTSOUND3DLISTENERRELEASEMETHODVALUE;

typedef struct DirectSound3DListenerGetAllParametersMethodValue
{
    LPDS3DLISTENER Descriptor;
} DIRECTSOUND3DLISTENERGETALLPARAMETERSMETHODVALUE, * LPDIRECTSOUND3DLISTENERGETALLPARAMETERSMETHODVALUE;

typedef struct DirectSound3DListenerGetDistanceFactorMethodValue
{
    LPD3DVALUE Factor;
} DIRECTSOUND3DLISTENERGETDISTANCEFACTORMETHODVALUE, * LPDIRECTSOUND3DLISTENERGETDISTANCEFACTORMETHODVALUE;

typedef struct DirectSound3DListenerGetDopplerFactorMethodValue
{
    LPD3DVALUE Factor;
} DIRECTSOUND3DLISTENERGETDOPPLERFACTORMETHODVALUE, * LPDIRECTSOUND3DLISTENERGETDOPPLERFACTORMETHODVALUE;

typedef struct DirectSound3DListenerGetOrientationMethodValue
{
    LPD3DVECTOR Front;
    LPD3DVECTOR Top;
} DIRECTSOUND3DLISTENERGETORIENTATIONMETHODVALUE, * LPDIRECTSOUND3DLISTENERGETORIENTATIONMETHODVALUE;

typedef struct DirectSound3DListenerGetPositionMethodValue
{
    LPD3DVECTOR Position;
} DIRECTSOUND3DLISTENERGETPOSITIONMETHODVALUE, * LPDIRECTSOUND3DLISTENERGETPOSITIONMETHODVALUE;

typedef struct DirectSound3DListenerGetRolloffFactorMethodValue
{
    LPD3DVALUE Factor;
} DIRECTSOUND3DLISTENERGETROLLOFFFACTORMETHODVALUE, * LPDIRECTSOUND3DLISTENERGETROLLOFFFACTORMETHODVALUE;

typedef struct DirectSound3DListenerGetVelocityMethodValue
{
    LPD3DVECTOR Velocity;
} DIRECTSOUND3DLISTENERGETVELOCITYMETHODVALUE, * LPDIRECTSOUND3DLISTENERGETVELOCITYMETHODVALUE;

typedef struct DirectSound3DListenerSetAllParametersMethodValue
{
    LPCDS3DLISTENER Descriptor;
    DWORD Options;
} DIRECTSOUND3DLISTENERSETALLPARAMETERSMETHODVALUE, * LPDIRECTSOUND3DLISTENERSETALLPARAMETERSMETHODVALUE;

typedef struct DirectSound3DListenerSetDistanceFactorMethodValue
{
    D3DVALUE Factor;
    DWORD Options;
} DIRECTSOUND3DLISTENERSETDISTANCEFACTORMETHODVALUE, * LPDIRECTSOUND3DLISTENERSETDISTANCEFACTORMETHODVALUE;

typedef struct DirectSound3DListenerSetDopplerFactorMethodValue
{
    D3DVALUE Factor;
    DWORD Options;
} DIRECTSOUND3DLISTENERSETDOPPLERFACTORMETHODVALUE, * LPDIRECTSOUND3DLISTENERSETDOPPLERFACTORMETHODVALUE;

typedef struct DirectSound3DListenerSetOrientationMethodValue
{
    D3DVALUE FrontX;
    D3DVALUE FrontY;
    D3DVALUE FrontZ;
    D3DVALUE TopX;
    D3DVALUE TopY;
    D3DVALUE TopZ;
    DWORD Options;
} DIRECTSOUND3DLISTENERSETORIENTATIONMETHODVALUE, * LPDIRECTSOUND3DLISTENERSETORIENTATIONMETHODVALUE;

typedef struct DirectSound3DListenerSetPositionMethodValue
{
    D3DVALUE X;
    D3DVALUE Y;
    D3DVALUE Z;
    DWORD Options;
} DIRECTSOUND3DLISTENERSETPOSITIONMETHODVALUE, * LPDIRECTSOUND3DLISTENERSETPOSITIONMETHODVALUE;

typedef struct DirectSound3DListenerSetRolloffFactorMethodValue
{
    D3DVALUE Factor;
    DWORD Options;
} DIRECTSOUND3DLISTENERSETROLLOFFFACTORMETHODVALUE, * LPDIRECTSOUND3DLISTENERSETROLLOFFFACTORMETHODVALUE;

typedef struct DirectSound3DListenerSetVelocityMethodValue
{
    D3DVALUE X;
    D3DVALUE Y;
    D3DVALUE Z;
    DWORD Options;
} DIRECTSOUND3DLISTENERSETVELOCITYMETHODVALUE, * LPDIRECTSOUND3DLISTENERSETVELOCITYMETHODVALUE;

typedef struct DirectSound3DListenerCommitDeferredSettingsMethodValue
{

} DIRECTSOUND3DLISTENERCOMMITDEFERREDSETTINGSMETHODVALUE, * LPDIRECTSOUND3DLISTENERCOMMITDEFERREDSETTINGSMETHODVALUE;