/*
Copyright (c) 2024 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "Base.hxx"

typedef struct Direct3DVolumeTexture8QueryInterfaceMethodValue
{
    GUID ID;
    LPVOID* Object;
} DIRECT3DVOLUMETEXTURE8QUERYINTERFACEMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8QUERYINTERFACEMETHODVALUE;

typedef struct Direct3DVolumeTexture8AddRefMethodValue
{

} DIRECT3DVOLUMETEXTURE8ADDREFMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8ADDREFMETHODVALUE;

typedef struct Direct3DVolumeTexture8ReleaseMethodValue
{

} DIRECT3DVOLUMETEXTURE8RELEASEMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8RELEASEMETHODVALUE;

typedef struct Direct3DVolumeTexture8GetDeviceMethodValue
{
    LPDIRECT3DDEVICE8* Device;
} DIRECT3DVOLUMETEXTURE8GETDEVICEMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8GETDEVICEMETHODVALUE;

typedef struct Direct3DVolumeTexture8SetPrivateDataMethodValue
{
    REFGUID ID;
    LPCVOID Data;
    DWORD Size;
    DWORD Options;
} DIRECT3DVOLUMETEXTURE8SETPRIVATEDATAMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8SETPRIVATEDATAMETHODVALUE;

typedef struct Direct3DVolumeTexture8GetPrivateDataMethodValue
{
    REFGUID ID;
    LPVOID Data;
    DWORD* Size;
} DIRECT3DVOLUMETEXTURE8GETPRIVATEDATAMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8GETPRIVATEDATAMETHODVALUE;

typedef struct Direct3DVolumeTexture8FreePrivateDataMethodValue
{
    REFGUID ID;
} DIRECT3DVOLUMETEXTURE8FREEPRIVATEDATAMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8FREEPRIVATEDATAMETHODVALUE;

typedef struct Direct3DVolumeTexture8SetPriorityMethodValue
{
    DWORD Priority;
} DIRECT3DVOLUMETEXTURE8SETPRIORITYMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8SETPRIORITYMETHODVALUE;

typedef struct Direct3DVolumeTexture8GetPriorityMethodValue
{

} DIRECT3DVOLUMETEXTURE8GETPRIORITYMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8GETPRIORITYMETHODVALUE;

typedef struct Direct3DVolumeTexture8PreLoadMethodValue
{

} DIRECT3DVOLUMETEXTURE8PRELOADMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8PRELOADMETHODVALUE;

typedef struct Direct3DVolumeTexture8GetTypeMethodValue
{

} DIRECT3DVOLUMETEXTURE8GETTYPEMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8GETTYPEMETHODVALUE;

typedef struct Direct3DVolumeTexture8SetLODMethodValue
{
    DWORD LOD;
} DIRECT3DVolumeTexture8SETLODMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8SETLODMETHODVALUE;

typedef struct Direct3DVolumeTexture8GetLODMethodValue
{

} DIRECT3DVOLUMETEXTURE8GETLODMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8GETLODMETHODVALUE;

typedef struct Direct3DVolumeTexture8GetLevelCountMethodValue
{

} DIRECT3DVOLUMETEXTURE8GETLEVELCOUNTMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8GETLEVELCOUNTMETHODVALUE;

typedef struct Direct3DVolumeTexture8GetLevelDescMethodValue
{
    UINT Level;
    D3DVOLUME_DESC* Desc;
} DIRECT3DVOLUMETEXTURE8GETLEVELDESCMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8GETLEVELDESCMETHODVALUE;

typedef struct Direct3DVolumeTexture8GetVolumeLevelMethodValue
{
    UINT Level;
    LPDIRECT3DVOLUME8* Volume;
} DIRECT3DVOLUMETEXTURE8GETVOLUMELEVELMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8GETVOLUMELEVELMETHODVALUE;

typedef struct Direct3DVolumeTexture8LockBoxMethodValue
{
    UINT Level;
    D3DLOCKED_BOX* Volume;
    CONST D3DBOX* Box;
    DWORD Options;
} DIRECT3DVOLUMETEXTURE8LOCKBOXMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8LOCKBOXMETHODVALUE;

typedef struct Direct3DVolumeTexture8UnlockBoxMethodValue
{
    UINT Level;
} DIRECT3DVOLUMETEXTURE8UNLOCKBOXMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8UNLOCKBOXMETHODVALUE;

typedef struct Direct3DVolumeTexture8AddDirtyBoxMethodValue
{
    CONST D3DBOX* Box;
} DIRECT3DVOLUMETEXTURE8ADDDIRTYBOXMETHODVALUE, * LPDIRECT3DVOLUMETEXTURE8ADDDIRTYBOXMETHODVALUE;