/*
Copyright (c) 2024 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "Base.hxx"

typedef struct DirectDrawSurface3QueryInterfaceMethodValue
{
    GUID ID;
    LPVOID* Object;
} DIRECTDRAWSURFACE3QUERYINTERFACEMETHODVALUE, * LPDIRECTDRAWSURFACE3QUERYINTERFACEMETHODVALUE;

typedef struct DirectDrawSurface3AddRefMethodValue
{

} DIRECTDRAWSURFACE3ADDREFMETHODVALUE, * LPDIRECTDRAWSURFACE3ADDREFMETHODVALUE;

typedef struct DirectDrawSurface3ReleaseMethodValue
{

} DIRECTDRAWSURFACE3RELEASEMETHODVALUE, * LPDIRECTDRAWSURFACE3RELEASEMETHODVALUE;

typedef struct DirectDrawSurface3AddAttachedSurfaceMethodValue
{
    LPDIRECTDRAWSURFACE3 Surface;
} DIRECTDRAWSURFACE3ADDATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACE3ADDATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurface3AddOverlayDirtyRectMethodValue
{
    LPRECT Rect;
} DIRECTDRAWSURFACE3ADDOVERLAYDIRTYRECTMETHODVALUE, * LPDIRECTDRAWSURFACE3ADDOVERLAYDIRTYRECTMETHODVALUE;

typedef struct DirectDrawSurface3BltMethodValue
{
    LPRECT Destination;
    LPDIRECTDRAWSURFACE3 Surface;
    LPRECT Source;
    DWORD Options;
    LPDDBLTFX Effect;
} DIRECTDRAWSURFACE3BLTMETHODVALUE, * LPDIRECTDRAWSURFACE3BLTMETHODVALUE;

typedef struct DirectDrawSurface3BltBatchMethodValue
{
    LPDDBLTBATCH Batch;
    DWORD Count;
    DWORD Options;
} DIRECTDRAWSURFACE3BLTBATCHMETHODVALUE, * LPDIRECTDRAWSURFACE3BLTBATCHMETHODVALUE;

typedef struct DirectDrawSurface3BltFastMethodValue
{
    DWORD X;
    DWORD Y;
    LPDIRECTDRAWSURFACE3 Surface;
    LPRECT Rect;
    DWORD Transparent;
} DIRECTDRAWSURFACE3BLTFASTMETHODVALUE, * LPDIRECTDRAWSURFACE3BLTFASTMETHODVALUE;

typedef struct DirectDrawSurface3DeleteAttachedSurfaceMethodValue
{
    DWORD Options;
    LPDIRECTDRAWSURFACE3 Surface;
} DIRECTDRAWSURFACE3DELETEATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACE3DELETEATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurface3EnumAttachedSurfacesMethodValue
{
    LPVOID Context;
    LPDDENUMSURFACESCALLBACK EnumSurfacesCallback;
} DIRECTDRAWSURFACE3ENUMATTACHEDSURFACESMETHODVALUE, * LPDIRECTDRAWSURFACE3ENUMATTACHEDSURFACESMETHODVALUE;

typedef struct DirectDrawSurface3EnumOverlayZOrdersMethodValue
{
    DWORD Options;
    LPVOID Context;
    LPDDENUMSURFACESCALLBACK Callback;
} DIRECTDRAWSURFACE3ENUMOVERLAYZORDERSMETHODVALUE, * LPDIRECTDRAWSURFACE3ENUMOVERLAYZORDERSMETHODVALUE;

typedef struct DirectDrawSurface3FlipMethodValue
{
    LPDIRECTDRAWSURFACE3 Surface;
    DWORD Options;
} DIRECTDRAWSURFACE3FLIPMETHODVALUE, * LPDIRECTDRAWSURFACE3FLIPMETHODVALUE;

typedef struct DirectDrawSurface3GetAttachedSurfaceMethodValue
{
    LPDDSCAPS Caps;
    LPDIRECTDRAWSURFACE3* Surface;
} DIRECTDRAWSURFACE3GETATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACE3GETATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurface3GetBltStatusMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE3GETBLTSTATUSMETHODVALUE, * LPDIRECTDRAWSURFACE3GETBLTSTATUSMETHODVALUE;

typedef struct DirectDrawSurface3GetCapsMethodValue
{
    LPDDSCAPS Caps;
} DIRECTDRAWSURFACE3GETCAPSMETHODVALUE, * LPDIRECTDRAWSURFACE3GETCAPSMETHODVALUE;

typedef struct DirectDrawSurface3GetClipperMethodValue
{
    LPDIRECTDRAWCLIPPER* Clipper;
} DIRECTDRAWSURFACE3GETCLIPPERMETHODVALUE, * LPDIRECTDRAWSURFACE3GETCLIPPERMETHODVALUE;

typedef struct DirectDrawSurface3GetColorKeyMethodValue
{
    DWORD Options;
    LPDDCOLORKEY ColorKey;
} DIRECTDRAWSURFACE3GETCOLORKEYMETHODVALUE, * LPDIRECTDRAWSURFACE3GETCOLORKEYMETHODVALUE;

typedef struct DirectDrawSurface3GetDCMethodValue
{
    HDC* DC;
} DIRECTDRAWSURFACE3GETDCMETHODVALUE, * LPDIRECTDRAWSURFACE3GETDCMETHODVALUE;

typedef struct DirectDrawSurface3GetFlipStatusMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE3GETFLIPSTATUSMETHODVALUE, * LPDIRECTDRAWSURFACE3GETFLIPSTATUSMETHODVALUE;

typedef struct DirectDrawSurface3GetOverlayPositionMethodValue
{
    LPLONG X;
    LPLONG Y;
} DIRECTDRAWSURFACE3GETOVERLAYPOSITIONMETHODVALUE, * LPDIRECTDRAWSURFACE3GETOVERLAYPOSITIONMETHODVALUE;

typedef struct DirectDrawSurface3GetPaletteMethodValue
{
    LPDIRECTDRAWPALETTE* Palette;
} DIRECTDRAWSURFACE3GETPALETTEMETHODVALUE, * LPDIRECTDRAWSURFACE3GETPALETTEMETHODVALUE;

typedef struct DirectDrawSurface3GetPixelFormatMethodValue
{
    LPDDPIXELFORMAT Format;
} DIRECTDRAWSURFACE3GETPIXELFORMATMETHODVALUE, * LPDIRECTDRAWSURFACE3GETPIXELFORMATMETHODVALUE;

typedef struct DirectDrawSurface3GetSurfaceDescMethodValue
{
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACE3GETSURFACEDESCMETHODVALUE, * LPDIRECTDRAWSURFACE3GETSURFACEDESCMETHODVALUE;

typedef struct DirectDrawSurface3InitializeMethodValue
{
    LPDIRECTDRAW Object;
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACE3INITIALIZEMETHODVALUE, * LPDIRECTDRAWSURFACE3INITIALIZEMETHODVALUE;

typedef struct DirectDrawSurface3IsLostMethodValue
{

} DIRECTDRAWSURFACE3ISLOSTMETHODVALUE, * LPDIRECTDRAWSURFACE3ISLOSTMETHODVALUE;

typedef struct DirectDrawSurface3LockMethodValue
{
    LPRECT Rect;
    LPDDSURFACEDESC Descriptor;
    DWORD Options;
    HANDLE Event;
} DIRECTDRAWSURFACE3LOCKMETHODVALUE, * LPDIRECTDRAWSURFACE3LOCKMETHODVALUE;

typedef struct DirectDrawSurface3ReleaseDCMethodValue
{
    HDC DC;
} DIRECTDRAWSURFACE3RELEASEDCMETHODVALUE, * LPDIRECTDRAWSURFACE3RELEASEDCMETHODVALUE;

typedef struct DirectDrawSurface3RestoreMethodValue
{

} DIRECTDRAWSURFACE3RESTOREMETHODVALUE, * LPDIRECTDRAWSURFACE3RESTOREMETHODVALUE;

typedef struct DirectDrawSurface3SetClipperMethodValue
{
    LPDIRECTDRAWCLIPPER Clipper;
} DIRECTDRAWSURFACE3SETCLIPPERMETHODVALUE, * LPDIRECTDRAWSURFACE3SETCLIPPERMETHODVALUE;

typedef struct DirectDrawSurface3SetColorKeyMethodValue
{
    DWORD Options;
    LPDDCOLORKEY ColorKey;
} DIRECTDRAWSURFACE3SETCOLORKEYMETHODVALUE, * LPDIRECTDRAWSURFACE3SETCOLORKEYMETHODVALUE;

typedef struct DirectDrawSurface3SetOverlayPositionMethodValue
{
    LONG X;
    LONG Y;
} DIRECTDRAWSURFACE3SETOVERLAYPOSITIONMETHODVALUE, * LPDIRECTDRAWSURFACE3SETOVERLAYPOSITIONMETHODVALUE;

typedef struct DirectDrawSurface3SetPaletteMethodValue
{
    LPDIRECTDRAWPALETTE Palette;
} DIRECTDRAWSURFACE3SETPALETTEMETHODVALUE, * LPDIRECTDRAWSURFACE3SETPALETTEMETHODVALUE;

typedef struct DirectDrawSurface3UnlockMethodValue
{
    LPVOID Value;
} DIRECTDRAWSURFACE3UNLOCKMETHODVALUE, * LPDIRECTDRAWSURFACE3UNLOCKMETHODVALUE;

typedef struct DirectDrawSurface3UpdateOverlayMethodValue
{
    LPRECT Source;
    LPDIRECTDRAWSURFACE3 Surface;
    LPRECT Destination;
    DWORD Options;
    LPDDOVERLAYFX Effect;
} DIRECTDRAWSURFACE3UPDATEOVERLAYMETHODVALUE, * LPDIRECTDRAWSURFACE3UPDATEOVERLAYMETHODVALUE;

typedef struct DirectDrawSurface3UpdateOverlayDisplayMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE3UPDATEOVERLAYDISPLAYMETHODVALUE, * LPDIRECTDRAWSURFACE3UPDATEOVERLAYDISPLAYMETHODVALUE;

typedef struct DirectDrawSurface3UpdateOverlayZOrderMethodValue
{
    DWORD Options;
    LPDIRECTDRAWSURFACE3 Surface;
} DIRECTDRAWSURFACE3UPDATEOVERLAYZORDERMETHODVALUE, * LPDIRECTDRAWSURFACE3UPDATEOVERLAYZORDERMETHODVALUE;

typedef struct DirectDrawSurface3GetDDInterfaceMethodValue
{
    LPVOID* Object;
} DIRECTDRAWSURFACE3GETDDINTERFACEMETHODVALUE, * LPDIRECTDRAWSURFACE3GETDDINTERFACEMETHODVALUE;

typedef struct DirectDrawSurface3PageLockMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE3PAGELOCKMETHODVALUE, * LPDIRECTDRAWSURFACE3PAGELOCKMETHODVALUE;

typedef struct DirectDrawSurface3PageUnlockMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE3PAGEUNLOCKMETHODVALUE, * LPDIRECTDRAWSURFACE3PAGEUNLOCKMETHODVALUE;

typedef struct DirectDrawSurface3SetSurfaceDescMethodValue
{
    LPDDSURFACEDESC Descriptor;
    DWORD Options;
} DIRECTDRAWSURFACE3SETSURFACEDESCMETHODVALUE, * LPDIRECTDRAWSURFACE3SETSURFACEDESCMETHODVALUE;

typedef struct DirectDrawSurface3EnumAttachedSurfacesMethodCallbackValue
{
    LPVOID Object;
    LPDIRECTDRAWSURFACE Surface;
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACE3ENUMATTACHEDSURFACESMETHODCALLBACKVALUE, * LPDIRECTDRAWSURFACE3ENUMATTACHEDSURFACESMETHODCALLBACKVALUE;

typedef struct DirectDrawSurface3EnumOverlayZOrdersMethodCallbackValue
{
    LPVOID Object;
    LPDIRECTDRAWSURFACE Surface;
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACE3ENUMOVERLAYZORDERSMETHODCALLBACKVALUE, * LPDIRECTDRAWSURFACE3ENUMOVERLAYZORDERSMETHODCALLBACKVALUE;