/*
Copyright (c) 2024 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "Base.hxx"

typedef struct DirectDrawSurfaceQueryInterfaceMethodValue
{
    GUID ID;
    LPVOID* Object;
} DIRECTDRAWSURFACEQUERYINTERFACEMETHODVALUE, * LPDIRECTDRAWSURFACEQUERYINTERFACEMETHODVALUE;

typedef struct DirectDrawSurfaceAddRefMethodValue
{

} DIRECTDRAWSURFACEADDREFMETHODVALUE, * LPDIRECTDRAWSURFACEADDREFMETHODVALUE;

typedef struct DirectDrawSurfaceReleaseMethodValue
{

} DIRECTDRAWSURFACERELEASEMETHODVALUE, * LPDIRECTDRAWSURFACERELEASEMETHODVALUE;

typedef struct DirectDrawSurfaceAddAttachedSurfaceMethodValue
{
    LPDIRECTDRAWSURFACE Surface;
} DIRECTDRAWSURFACEADDATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACEADDATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurfaceAddOverlayDirtyRectMethodValue
{
    LPRECT Rect;
} DIRECTDRAWSURFACEADDOVERLAYDIRTYRECTMETHODVALUE, * LPDIRECTDRAWSURFACEADDOVERLAYDIRTYRECTMETHODVALUE;

typedef struct DirectDrawSurfaceBltMethodValue
{
    LPRECT Destination;
    LPDIRECTDRAWSURFACE Surface;
    LPRECT Source;
    DWORD Options;
    LPDDBLTFX Effect;
} DIRECTDRAWSURFACEBLTMETHODVALUE, * LPDIRECTDRAWSURFACEBLTMETHODVALUE;

typedef struct DirectDrawSurfaceBltBatchMethodValue
{
    LPDDBLTBATCH Batch;
    DWORD Count;
    DWORD Options;
} DIRECTDRAWSURFACEBLTBATCHMETHODVALUE, * LPDIRECTDRAWSURFACEBLTBATCHMETHODVALUE;

typedef struct DirectDrawSurfaceBltFastMethodValue
{
    DWORD X;
    DWORD Y;
    LPDIRECTDRAWSURFACE Surface;
    LPRECT Rect;
    DWORD Transparent;
} DIRECTDRAWSURFACEBLTFASTMETHODVALUE, * LPDIRECTDRAWSURFACEBLTFASTMETHODVALUE;

typedef struct DirectDrawSurfaceDeleteAttachedSurfaceMethodValue
{
    DWORD Options;
    LPDIRECTDRAWSURFACE Surface;
} DIRECTDRAWSURFACEDELETEATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACEDELETEATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurfaceEnumAttachedSurfacesMethodValue
{
    LPVOID Context;
    LPDDENUMSURFACESCALLBACK EnumSurfacesCallback;
} DIRECTDRAWSURFACEENUMATTACHEDSURFACESMETHODVALUE, * LPDIRECTDRAWSURFACEENUMATTACHEDSURFACESMETHODVALUE;

typedef struct DirectDrawSurfaceEnumOverlayZOrdersMethodValue
{
    DWORD Options;
    LPVOID Context;
    LPDDENUMSURFACESCALLBACK Callback;
} DIRECTDRAWSURFACEENUMOVERLAYZORDERSMETHODVALUE, * LPDIRECTDRAWSURFACEENUMOVERLAYZORDERSMETHODVALUE;

typedef struct DirectDrawSurfaceFlipMethodValue
{
    LPDIRECTDRAWSURFACE Surface;
    DWORD Options;
} DIRECTDRAWSURFACEFLIPMETHODVALUE, * LPDIRECTDRAWSURFACEFLIPMETHODVALUE;

typedef struct DirectDrawSurfaceGetAttachedSurfaceMethodValue
{
    LPDDSCAPS Caps;
    LPDIRECTDRAWSURFACE* Surface;
} DIRECTDRAWSURFACEGETATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACEGETATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurfaceGetBltStatusMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACEGETBLTSTATUSMETHODVALUE, * LPDIRECTDRAWSURFACEGETBLTSTATUSMETHODVALUE;

typedef struct DirectDrawSurfaceGetCapsMethodValue
{
    LPDDSCAPS Caps;
} DIRECTDRAWSURFACEGETCAPSMETHODVALUE, * LPDIRECTDRAWSURFACEGETCAPSMETHODVALUE;

typedef struct DirectDrawSurfaceGetClipperMethodValue
{
    LPDIRECTDRAWCLIPPER* Clipper;
} DIRECTDRAWSURFACEGETCLIPPERMETHODVALUE, * LPDIRECTDRAWSURFACEGETCLIPPERMETHODVALUE;

typedef struct DirectDrawSurfaceGetColorKeyMethodValue
{
    DWORD Options;
    LPDDCOLORKEY ColorKey;
} DIRECTDRAWSURFACEGETCOLORKEYMETHODVALUE, * LPDIRECTDRAWSURFACEGETCOLORKEYMETHODVALUE;

typedef struct DirectDrawSurfaceGetDCMethodValue
{
    HDC* DC;
} DIRECTDRAWSURFACEGETDCMETHODVALUE, * LPDIRECTDRAWSURFACEGETDCMETHODVALUE;

typedef struct DirectDrawSurfaceGetFlipStatusMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACEGETFLIPSTATUSMETHODVALUE, * LPDIRECTDRAWSURFACEGETFLIPSTATUSMETHODVALUE;

typedef struct DirectDrawSurfaceGetOverlayPositionMethodValue
{
    LPLONG X;
    LPLONG Y;
} DIRECTDRAWSURFACEGETOVERLAYPOSITIONMETHODVALUE, * LPDIRECTDRAWSURFACEGETOVERLAYPOSITIONMETHODVALUE;

typedef struct DirectDrawSurfaceGetPaletteMethodValue
{
    LPDIRECTDRAWPALETTE* Palette;
} DIRECTDRAWSURFACEGETPALETTEMETHODVALUE, * LPDIRECTDRAWSURFACEGETPALETTEMETHODVALUE;

typedef struct DirectDrawSurfaceGetPixelFormatMethodValue
{
    LPDDPIXELFORMAT Format;
} DIRECTDRAWSURFACEGETPIXELFORMATMETHODVALUE, * LPDIRECTDRAWSURFACEGETPIXELFORMATMETHODVALUE;

typedef struct DirectDrawSurfaceGetSurfaceDescMethodValue
{
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACEGETSURFACEDESCMETHODVALUE, * LPDIRECTDRAWSURFACEGETSURFACEDESCMETHODVALUE;

typedef struct DirectDrawSurfaceInitializeMethodValue
{
    LPDIRECTDRAW Object;
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACEINITIALIZEMETHODVALUE, * LPDIRECTDRAWSURFACEINITIALIZEMETHODVALUE;

typedef struct DirectDrawSurfaceIsLostMethodValue
{

} DIRECTDRAWSURFACEISLOSTMETHODVALUE, * LPDIRECTDRAWSURFACEISLOSTMETHODVALUE;

typedef struct DirectDrawSurfaceLockMethodValue
{
    LPRECT Rect;
    LPDDSURFACEDESC Descriptor;
    DWORD Options;
    HANDLE Event;
} DIRECTDRAWSURFACELOCKMETHODVALUE, * LPDIRECTDRAWSURFACELOCKMETHODVALUE;

typedef struct DirectDrawSurfaceReleaseDCMethodValue
{
    HDC DC;
} DIRECTDRAWSURFACERELEASEDCMETHODVALUE, * LPDIRECTDRAWSURFACERELEASEDCMETHODVALUE;

typedef struct DirectDrawSurfaceRestoreMethodValue
{

} DIRECTDRAWSURFACERESTOREMETHODVALUE, * LPDIRECTDRAWSURFACERESTOREMETHODVALUE;

typedef struct DirectDrawSurfaceSetClipperMethodValue
{
    LPDIRECTDRAWCLIPPER Clipper;
} DIRECTDRAWSURFACESETCLIPPERMETHODVALUE, * LPDIRECTDRAWSURFACESETCLIPPERMETHODVALUE;

typedef struct DirectDrawSurfaceSetColorKeyMethodValue
{
    DWORD Options;
    LPDDCOLORKEY ColorKey;
} DIRECTDRAWSURFACESETCOLORKEYMETHODVALUE, * LPDIRECTDRAWSURFACESETCOLORKEYMETHODVALUE;

typedef struct DirectDrawSurfaceSetOverlayPositionMethodValue
{
    LONG X;
    LONG Y;
} DIRECTDRAWSURFACESETOVERLAYPOSITIONMETHODVALUE, * LPDIRECTDRAWSURFACESETOVERLAYPOSITIONMETHODVALUE;

typedef struct DirectDrawSurfaceSetPaletteMethodValue
{
    LPDIRECTDRAWPALETTE Palette;
} DIRECTDRAWSURFACESETPALETTEMETHODVALUE, * LPDIRECTDRAWSURFACESETPALETTEMETHODVALUE;

typedef struct DirectDrawSurfaceUnlockMethodValue
{
    LPVOID Value;
} DIRECTDRAWSURFACEUNLOCKMETHODVALUE, * LPDIRECTDRAWSURFACEUNLOCKMETHODVALUE;

typedef struct DirectDrawSurfaceUpdateOverlayMethodValue
{
    LPRECT Source;
    LPDIRECTDRAWSURFACE Surface;
    LPRECT Destination;
    DWORD Options;
    LPDDOVERLAYFX Effect;
} DIRECTDRAWSURFACEUPDATEOVERLAYMETHODVALUE, * LPDIRECTDRAWSURFACEUPDATEOVERLAYMETHODVALUE;

typedef struct DirectDrawSurfaceUpdateOverlayDisplayMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACEUPDATEOVERLAYDISPLAYMETHODVALUE, * LPDIRECTDRAWSURFACEUPDATEOVERLAYDISPLAYMETHODVALUE;

typedef struct DirectDrawSurfaceUpdateOverlayZOrderMethodValue
{
    DWORD Options;
    LPDIRECTDRAWSURFACE Surface;
} DIRECTDRAWSURFACEUPDATEOVERLAYZORDERMETHODVALUE, * LPDIRECTDRAWSURFACEUPDATEOVERLAYZORDERMETHODVALUE;

typedef struct DirectDrawSurfaceEnumAttachedSurfacesMethodCallbackValue
{
    LPVOID Object;
    LPDIRECTDRAWSURFACE Surface;
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACEENUMATTACHEDSURFACESMETHODCALLBACKVALUE, * LPDIRECTDRAWSURFACEENUMATTACHEDSURFACESMETHODCALLBACKVALUE;

typedef struct DirectDrawSurfaceEnumOverlayZOrdersMethodCallbackValue
{
    LPVOID Object;
    LPDIRECTDRAWSURFACE Surface;
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACEENUMOVERLAYZORDERSMETHODCALLBACKVALUE, * LPDIRECTDRAWSURFACEENUMOVERLAYZORDERSMETHODCALLBACKVALUE;