/*
Copyright (c) 2024 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "Base.hxx"

typedef struct DirectDraw7QueryInterfaceMethodValue
{
    GUID ID;
    LPVOID* Object;
} DIRECTDRAW7QUERYINTERFACEMETHODVALUE, * LPDIRECTDRAW7QUERYINTERFACEMETHODVALUE;

typedef struct DirectDraw7AddRefMethodValue
{

} DIRECTDRAW7ADDREFMETHODVALUE, * LPDIRECTDRAW7ADDREFMETHODVALUE;

typedef struct DirectDraw7ReleaseMethodValue
{

} DIRECTDRAW7RELEASEMETHODVALUE, * LPDIRECTDRAW7RELEASEMETHODVALUE;

typedef struct DirectDraw7CompactMethodValue
{

} DIRECTDRAW7COMPACTMETHODVALUE, * LPDIRECTDRAW7COMPACTMETHODVALUE;

typedef struct DirectDraw7CreateClipperMethodValue
{
    DWORD Options;
    LPDIRECTDRAWCLIPPER* Object;
    LPUNKNOWN Unknown;
} DIRECTDRAW7CREATECLIPPERMETHODVALUE, * LPDIRECTDRAW7CREATECLIPPERMETHODVALUE;

typedef struct DirectDraw7CreatePaletteMethodValue
{
    DWORD Options;
    LPPALETTEENTRY Colors;
    LPDIRECTDRAWPALETTE* Object;
    LPUNKNOWN Unknown;
} DIRECTDRAW7CREATEPALETTEMETHODVALUE, * LPDIRECTDRAW7CREATEPALETTEMETHODVALUE;

typedef struct DirectDraw7CreateSurfaceMethodValue
{
    LPDDSURFACEDESC2 Descriptor;
    LPDIRECTDRAWSURFACE7* Object;
    LPUNKNOWN Unknown;
} DIRECTDRAW7CREATESURFACEMETHODVALUE, * LPDIRECTDRAW7CREATESURFACEMETHODVALUE;

typedef struct DirectDraw7DuplicateSurfaceMethodValue
{
    LPDIRECTDRAWSURFACE7 Object;
    LPDIRECTDRAWSURFACE7* Duplicate;
} DIRECTDRAW7DUPLICATESURFACEMETHODVALUE, * LPDIRECTDRAW7DUPLICATESURFACEMETHODVALUE;

typedef struct DirectDraw7EnumDisplayModesMethodValue
{
    DWORD Options;
    LPDDSURFACEDESC2 Descriptor;
    LPVOID Context;
    LPDDENUMMODESCALLBACK2 EnumModesCallback;
} DIRECTDRAW7ENUMDISPLAYMODESMETHODVALUE, * LPDIRECTDRAW7ENUMDISPLAYMODESMETHODVALUE;

typedef struct DirectDraw7EnumSurfacesMethodValue
{
    DWORD Options;
    LPDDSURFACEDESC2 Descriptor;
    LPVOID Context;
    LPDDENUMSURFACESCALLBACK7 EnumSurfacesCallback;
} DIRECTDRAW7ENUMSURFACESMETHODVALUE, * LPDIRECTDRAW7ENUMSURFACESMETHODVALUE;

typedef struct DirectDraw7FlipToGDISurfaceMethodValue
{

} DIRECTDRAW7FLIPTOGDISURFACEMETHODVALUE, * LPDIRECTDRAW7FLIPTOGDISURFACEMETHODVALUE;

typedef struct DirectDraw7GetCapsMethodValue
{
    LPDDCAPS AccelerationDriverCaps;
    LPDDCAPS EmulationDricerCaps;
} DIRECTDRAW7GETCAPSMETHODVALUE, * LPDIRECTDRAW7GETCAPSMETHODVALUE;

typedef struct DirectDraw7GetDisplayModeMethodValue
{
    LPDDSURFACEDESC2 Descriptor;
} DIRECTDRAW7GETDISPLAYMODEMETHODVALUE, * LPDIRECTDRAW7GETDISPLAYMODEMETHODVALUE;

typedef struct DirectDraw7GetFourCCCodesMethodValue
{
    LPDWORD Count;
    LPDWORD Codes;
} DIRECTDRAW7GETFOURCCCODESMETHODVALUE, * LPDIRECTDRAW7GETFOURCCCODESMETHODVALUE;

typedef struct DirectDraw7GetGDISurfaceMethodValue
{
    LPDIRECTDRAWSURFACE7* Surface;
} DIRECTDRAW7GETGDISURFACEMETHODVALUE, * LPDIRECTDRAW7GETGDISURFACEMETHODVALUE;

typedef struct DirectDraw7GetMonitorFrequencyMethodValue
{
    LPDWORD Frequency;
} DIRECTDRAW7GETMONITORFREQUENCYMETHODVALUE, * LPDIRECTDRAW7GETMONITORFREQUENCYMETHODVALUE;

typedef struct DirectDraw7GetScanLineMethodValue
{
    LPDWORD ScanLine;
} DIRECTDRAW7GETSCANLINEMETHODVALUE, * LPDIRECTDRAW7GETSCANLINEMETHODVALUE;

typedef struct DirectDraw7GetVerticalBlankStatusMethodValue
{
    LPBOOL IsInVerticalBlank;
} DIRECTDRAW7GETVERTICALBLANKSTATUSMETHODVALUE, * LPDIRECTDRAW7GETVERTICALBLANKSTATUSMETHODVALUE;

typedef struct DirectDraw7InitializeMethodValue
{
    LPGUID ID;
} DIRECTDRAW7INITIALIZEMETHODVALUE, * LPDIRECTDRAW7INITIALIZEMETHODVALUE;

typedef struct DirectDraw7RestoreDisplayModeMethodValue
{

} DIRECTDRAW7RESTOREDISPLAYMODEMETHODVALUE, * LPDIRECTDRAW7RESTOREDISPLAYMODEMETHODVALUE;

typedef struct DirectDraw7SetCooperativeLevelMethodValue
{
    HWND Window;
    DWORD Options;
} DIRECTDRAW7SETCOOPERATIVELEVELMETHODVALUE, * LPDIRECTDRAW7SETCOOPERATIVELEVELMETHODVALUE;

typedef struct DirectDraw7SetDisplayModeMethodValue
{
    DWORD Width;
    DWORD Height;
    DWORD Bits;
    DWORD RefreshRate;
    DWORD Options;
} DIRECTDRAW7SETDISPLAYMODEMETHODVALUE, * LPDIRECTDRAW7SETDISPLAYMODEMETHODVALUE;

typedef struct DirectDraw7WaitForVerticalBlankMethodValue
{
    DWORD Options;
    HANDLE Event;
} DIRECTDRAW7WAITFORVERTICALBLANKMETHODVALUE, * LPDIRECTDRAW7WAITFORVERTICALBLANKMETHODVALUE;

typedef struct DirectDraw7GetAvailableVidMemMethodValue
{
    LPDDSCAPS2 Caps;
    LPDWORD Total;
    LPDWORD Free;
} DIRECTDRAW7GETAVAILABLEVIDMEMMETHODVALUE, * LPDIRECTDRAW7GETAVAILABLEVIDMEMMETHODVALUE;

typedef struct DirectDraw7GetSurfaceFromDCMethodValue
{
    HDC DC;
    LPDIRECTDRAWSURFACE7* Surface;
} DIRECTDRAW7GETSURFACEFROMDCMETHODVALUE, * LPDIRECTDRAW7GETSURFACEFROMDCMETHODVALUE;

typedef struct DirectDraw7RestoreAllSurfacesMethodValue
{

} DIRECTDRAW7RESTOREALLSURFACESMETHODVALUE, * LPDIRECTDRAW7RESTOREALLSURFACESMETHODVALUE;

typedef struct DirectDraw7TestCooperativeLevelMethodValue
{

} DIRECTDRAW7TESTCOOPERATIVELEVELMETHODVALUE, * LPDIRECTDRAW7TESTCOOPERATIVELEVELMETHODVALUE;

typedef struct DirectDraw7GetDeviceIdentifierMethodValue
{
    LPDDDEVICEIDENTIFIER2 Identifier;
    DWORD Options;
} DIRECTDRAW7GETDEVICEIDENTIFIERMETHODVALUE, * LPDIRECTDRAW7GETDEVICEIDENTIFIERMETHODVALUE;

typedef struct DirectDraw7StartModeTestMethodValue
{
    LPSIZE Modes;
    DWORD Count;
    DWORD Options;
} DIRECTDRAW7STARTMODETESTMETHODVALUE, * LPDIRECTDRAW7STARTMODETESTMETHODVALUE;

typedef struct DirectDraw7EvaluateModeMethodValue
{
    DWORD Options;
    LPDWORD SecondsUntilTimeout;
} DIRECTDRAW7EVALUATEMODEMETHODVALUE, * LPDIRECTDRAW7EVALUATEMODEMETHODVALUE;

typedef struct DirectDraw7EnumDisplayModesMethodCallbackValue
{
    LPVOID Object;
    LPDDSURFACEDESC2 Descriptor;
} DIRECTDRAW7ENUMDISPLAYMODESMETHODCALLBACKVALUE, * LPDIRECTDRAW7ENUMDISPLAYMODESMETHODCALLBACKVALUE;

typedef struct DirectDraw7EnumSurfacesMethodCallbackValue
{
    LPVOID Object;
    LPDIRECTDRAWSURFACE7 Surface;
    LPDDSURFACEDESC2 Descriptor;
} DIRECTDRAW7ENUMSURFACESMETHODCALLBACKVALUE, * LPDIRECTDRAW7ENUMSURFACESMETHODCALLBACKVALUE;