/*
Copyright (c) 2024 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "Base.hxx"

typedef struct DirectDrawVideoPortQueryInterfaceMethodValue
{
    GUID ID;
    LPVOID* Object;
} DIRECTDRAWVIDEOPORTQUERYINTERFACEMETHODVALUE, * LPDIRECTDRAWVIDEOPORTQUERYINTERFACEMETHODVALUE;

typedef struct DirectDrawVideoPortAddRefMethodValue
{

} DIRECTDRAWVIDEOPORTADDREFMETHODVALUE, * LPDIRECTDRAWVIDEOPORTADDREFMETHODVALUE;

typedef struct DirectDrawVideoPortReleaseMethodValue
{

} DIRECTDRAWVIDEOPORTRELEASEMETHODVALUE, * LPDIRECTDRAWVIDEOPORTRELEASEMETHODVALUE;

typedef struct DirectDrawVideoPortFlipMethodValue
{
    LPDIRECTDRAWSURFACE Surface;
    DWORD Options;
} DIRECTDRAWVIDEOPORTFLIPMETHODVALUE, * LPDIRECTDRAWVIDEOPORTFLIPMETHODVALUE;

typedef struct DirectDrawVideoPortGetBandwidthInfoMethodValue
{
    LPDDPIXELFORMAT Format;
    DWORD Width;
    DWORD Height;
    DWORD Options;
    LPDDVIDEOPORTBANDWIDTH Bandwidth;
} DIRECTDRAWVIDEOPORTGETBANDWIDTHINFOMETHODVALUE, * LPDIRECTDRAWVIDEOPORTGETBANDWIDTHINFOMETHODVALUE;

typedef struct DirectDrawVideoPortGetColorControlsMethodValue
{
    LPDDCOLORCONTROL ColorControl;
} DIRECTDRAWVIDEOPORTGETCOLORCONTROLSMETHODVALUE, * LPDIRECTDRAWVIDEOPORTGETCOLORCONTROLSMETHODVALUE;

typedef struct DirectDrawVideoPortGetInputFormatsMethodValue
{
    LPDWORD Count;
    LPDDPIXELFORMAT Formats;
    DWORD Options;
} DIRECTDRAWVIDEOPORTGETINPUTFORMATSMETHODVALUE, * LPDIRECTDRAWVIDEOPORTGETINPUTFORMATSMETHODVALUE;

typedef struct DirectDrawVideoPortGetOutputFormatsMethodValue
{
    LPDDPIXELFORMAT Input;
    LPDWORD Count;
    LPDDPIXELFORMAT Formats;
    DWORD Options;
} DIRECTDRAWVIDEOPORTGETOUTPUTFORMATSMETHODVALUE, * LPDIRECTDRAWVIDEOPORTGETOUTPUTFORMATSMETHODVALUE;

typedef struct DirectDrawVideoPortGetFieldPolarityMethodValue
{
    LPBOOL FieldPolarity;
} DIRECTDRAWVIDEOPORTGETFIELDPOLARITYMETHODVALUE, * LPDIRECTDRAWVIDEOPORTGETFIELDPOLARITYMETHODVALUE;

typedef struct DirectDrawVideoPortGetVideoLineMethodValue
{
    LPDWORD Line;
} DIRECTDRAWVIDEOPORTGETVIDEOLINEMETHODVALUE, * LPDIRECTDRAWVIDEOPORTGETVIDEOLINEMETHODVALUE;

typedef struct DirectDrawVideoPortGetVideoSignalStatusMethodValue
{
    LPDWORD Status;
} DIRECTDRAWVIDEOPORTGETVIDEOSIGNALSTATUSMETHODVALUE, * LPDIRECTDRAWVIDEOPORTGETVIDEOSIGNALSTATUSMETHODVALUE;

typedef struct DirectDrawVideoPortSetColorControlsMethodValue
{
    LPDDCOLORCONTROL ColorControl;
} DIRECTDRAWVIDEOPORTSETCOLORCONTROLSMETHODVALUE, * LPDIRECTDRAWVIDEOPORTSETCOLORCONTROLSMETHODVALUE;

typedef struct DirectDrawVideoPortSetTargetSurfaceMethodValue
{
    LPDIRECTDRAWSURFACE Surface;
    DWORD Options;
} DIRECTDRAWVIDEOPORTSETTARGETSURFACEMETHODVALUE, * LPDIRECTDRAWVIDEOPORTSETTARGETSURFACEMETHODVALUE;

typedef struct DirectDrawVideoPortStartVideoMethodValue
{
    LPDDVIDEOPORTINFO VideoInfo;
} DIRECTDRAWVIDEOPORTSTARTVIDEOMETHODVALUE, * LPDIRECTDRAWVIDEOPORTSTARTVIDEOMETHODVALUE;

typedef struct DirectDrawVideoPortStopVideoMethodValue
{

} DIRECTDRAWVIDEOPORTSTOPVIDEOMETHODVALUE, * LPDIRECTDRAWVIDEOPORTSTOPVIDEOMETHODVALUE;

typedef struct DirectDrawVideoPortUpdateVideoMethodValue
{
    LPDDVIDEOPORTINFO VideoInfo;
} DIRECTDRAWVIDEOPORTUPDATEVIDEOMETHODVALUE, * LPDIRECTDRAWVIDEOPORTUPDATEVIDEOMETHODVALUE;

typedef struct DirectDrawVideoPortWaitForSyncMethodValue
{
    DWORD Options;
    DWORD Line;
    DWORD Timeout;
} DIRECTDRAWVIDEOPORTWAITFORSYNCMETHODVALUE, * LPDIRECTDRAWVIDEOPORTWAITFORSYNCMETHODVALUE;