/*
Copyright (c) 2024 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "Base.hxx"

typedef struct Direct3DViewportQueryInterfaceMethodValue
{
    GUID ID;
    LPVOID* Object;
} DIRECT3DVIEWPORTQUERYINTERFACEMETHODVALUE, * LPDIRECT3DVIEWPORTQUERYINTERFACEMETHODVALUE;

typedef struct Direct3DViewportAddRefMethodValue
{

} DIRECT3DVIEWPORTADDREFMETHODVALUE, * LPDIRECT3DVIEWPORTADDREFMETHODVALUE;

typedef struct Direct3DViewportReleaseMethodValue
{

} DIRECT3DVIEWPORTRELEASEMETHODVALUE, * LPDIRECT3DVIEWPORTRELEASEMETHODVALUE;

typedef struct Direct3DViewportInitializeMethodValue
{
    LPDIRECT3D Object;
} DIRECT3DVIEWPORTINITIALIZEMETHODVALUE, * LPDIRECT3DVIEWPORTINITIALIZEMETHODVALUE;

typedef struct Direct3DViewportGetViewportMethodValue
{
    LPD3DVIEWPORT ViewPort;
} DIRECT3DVIEWPORTGETVIEWPORTMETHODVALUE, * LPDIRECT3DVIEWPORTGETVIEWPORTMETHODVALUE;

typedef struct Direct3DViewportSetViewportMethodValue
{
    LPD3DVIEWPORT ViewPort;
} DIRECT3DVIEWPORTSETVIEWPORTMETHODVALUE, * LPDIRECT3DVIEWPORTSETVIEWPORTMETHODVALUE;

typedef struct Direct3DViewportTransformVerticesMethodValue
{
    DWORD Count;
    LPD3DTRANSFORMDATA Transform;
    DWORD Options;
    LPDWORD Offscreen;
} DIRECT3DVIEWPORTTRANSFORMVERTICESMETHODVALUE, * LPDIRECT3DVIEWPORTTRANSFORMVERTICESMETHODVALUE;

typedef struct Direct3DViewportLightElementsMethodValue
{
    DWORD Count;
    LPD3DLIGHTDATA Value;
} DIRECT3DVIEWPORTLIGHTELEMENTSMETHODVALUE, * LPDIRECT3DVIEWPORTLIGHTELEMENTSMETHODVALUE;

typedef struct Direct3DViewportSetBackgroundMethodValue
{
    D3DMATERIALHANDLE Handle;
} DIRECT3DVIEWPORTSETBACKGROUNDMETHODVALUE, * LPDIRECT3DVIEWPORTSETBACKGROUNDMETHODVALUE;

typedef struct Direct3DViewportGetBackgroundMethodValue
{
    LPD3DMATERIALHANDLE Handle;
    LPBOOL Valid;
} DIRECT3DVIEWPORTGETBACKGROUNDMETHODVALUE, * LPDIRECT3DVIEWPORTGETBACKGROUNDMETHODVALUE;

typedef struct Direct3DViewportSetBackgroundDepthMethodValue
{
    LPDIRECTDRAWSURFACE Surface;
} DIRECT3DVIEWPORTSETBACKGROUNDDEPTHMETHODVALUE, * LPDIRECT3DVIEWPORTSETBACKGROUNDDEPTHMETHODVALUE;

typedef struct Direct3DViewportGetBackgroundDepthMethodValue
{
    LPDIRECTDRAWSURFACE* Surface;
    LPBOOL Valid;
} DIRECT3DVIEWPORTGETBACKGROUNDDEPTHMETHODVALUE, * LPDIRECT3DVIEWPORTGETBACKGROUNDDEPTHMETHODVALUE;

typedef struct Direct3DViewportClearMethodValue
{
    DWORD Count;
    LPD3DRECT Rects;
    DWORD Options;
} DIRECT3DVIEWPORTCLEARMETHODVALUE, * LPDIRECT3DVIEWPORTCLEARMETHODVALUE;

typedef struct Direct3DViewportAddLightMethodValue
{
    LPDIRECT3DLIGHT Light;
} DIRECT3DVIEWPORTADDLIGHTMETHODVALUE, * LPDIRECT3DVIEWPORTADDLIGHTMETHODVALUE;

typedef struct Direct3DViewportDeleteLightMethodValue
{
    LPDIRECT3DLIGHT Light;
} DIRECT3DVIEWPORTDELETELIGHTMETHODVALUE, * LPDIRECT3DVIEWPORTDELETELIGHTMETHODVALUE;

typedef struct Direct3DViewportNextLightMethodValue
{
    LPDIRECT3DLIGHT Light;
    LPDIRECT3DLIGHT* NextLight;
    DWORD Options;
} DIRECT3DVIEWPORTNEXTLIGHTMETHODVALUE, * LPDIRECT3DVIEWPORTNEXTLIGHTMETHODVALUE;