/*
Copyright (c) 2024 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "Base.hxx"

typedef struct DirectDrawSurface7QueryInterfaceMethodValue
{
    GUID ID;
    LPVOID* Object;
} DIRECTDRAWSURFACE7QUERYINTERFACEMETHODVALUE, * LPDIRECTDRAWSURFACE7QUERYINTERFACEMETHODVALUE;

typedef struct DirectDrawSurface7AddRefMethodValue
{

} DIRECTDRAWSURFACE7ADDREFMETHODVALUE, * LPDIRECTDRAWSURFACE7ADDREFMETHODVALUE;

typedef struct DirectDrawSurface7ReleaseMethodValue
{

} DIRECTDRAWSURFACE7RELEASEMETHODVALUE, * LPDIRECTDRAWSURFACE7RELEASEMETHODVALUE;

typedef struct DirectDrawSurface7AddAttachedSurfaceMethodValue
{
    LPDIRECTDRAWSURFACE7 Surface;
} DIRECTDRAWSURFACE7ADDATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACE7ADDATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurface7AddOverlayDirtyRectMethodValue
{
    LPRECT Rect;
} DIRECTDRAWSURFACE7ADDOVERLAYDIRTYRECTMETHODVALUE, * LPDIRECTDRAWSURFACE7ADDOVERLAYDIRTYRECTMETHODVALUE;

typedef struct DirectDrawSurface7BltMethodValue
{
    LPRECT Destination;
    LPDIRECTDRAWSURFACE7 Surface;
    LPRECT Source;
    DWORD Options;
    LPDDBLTFX Effect;
} DIRECTDRAWSURFACE7BLTMETHODVALUE, * LPDIRECTDRAWSURFACE7BLTMETHODVALUE;

typedef struct DirectDrawSurface7BltBatchMethodValue
{
    LPDDBLTBATCH Batch;
    DWORD Count;
    DWORD Options;
} DIRECTDRAWSURFACE7BLTBATCHMETHODVALUE, * LPDIRECTDRAWSURFACE7BLTBATCHMETHODVALUE;

typedef struct DirectDrawSurface7BltFastMethodValue
{
    DWORD X;
    DWORD Y;
    LPDIRECTDRAWSURFACE7 Surface;
    LPRECT Rect;
    DWORD Transparent;
} DIRECTDRAWSURFACE7BLTFASTMETHODVALUE, * LPDIRECTDRAWSURFACE7BLTFASTMETHODVALUE;

typedef struct DirectDrawSurface7DeleteAttachedSurfaceMethodValue
{
    DWORD Options;
    LPDIRECTDRAWSURFACE7 Surface;
} DIRECTDRAWSURFACE7DELETEATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACE7DELETEATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurface7EnumAttachedSurfacesMethodValue
{
    LPVOID Context;
    LPDDENUMSURFACESCALLBACK7 EnumSurfacesCallback;
} DIRECTDRAWSURFACE7ENUMATTACHEDSURFACESMETHODVALUE, * LPDIRECTDRAWSURFACE7ENUMATTACHEDSURFACESMETHODVALUE;

typedef struct DirectDrawSurface7EnumOverlayZOrdersMethodValue
{
    DWORD Options;
    LPVOID Context;
    LPDDENUMSURFACESCALLBACK7 Callback;
} DIRECTDRAWSURFACE7ENUMOVERLAYZORDERSMETHODVALUE, * LPDIRECTDRAWSURFACE7ENUMOVERLAYZORDERSMETHODVALUE;

typedef struct DirectDrawSurface7FlipMethodValue
{
    LPDIRECTDRAWSURFACE7 Surface;
    DWORD Options;
} DIRECTDRAWSURFACE7FLIPMETHODVALUE, * LPDIRECTDRAWSURFACE7FLIPMETHODVALUE;

typedef struct DirectDrawSurface7GetAttachedSurfaceMethodValue
{
    LPDDSCAPS2 Caps;
    LPDIRECTDRAWSURFACE7* Surface;
} DIRECTDRAWSURFACE7GETATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACE7GETATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurface7GetBltStatusMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE7GETBLTSTATUSMETHODVALUE, * LPDIRECTDRAWSURFACE7GETBLTSTATUSMETHODVALUE;

typedef struct DirectDrawSurface7GetCapsMethodValue
{
    LPDDSCAPS2 Caps;
} DIRECTDRAWSURFACE7GETCAPSMETHODVALUE, * LPDIRECTDRAWSURFACE7GETCAPSMETHODVALUE;

typedef struct DirectDrawSurface7GetClipperMethodValue
{
    LPDIRECTDRAWCLIPPER* Clipper;
} DIRECTDRAWSURFACE7GETCLIPPERMETHODVALUE, * LPDIRECTDRAWSURFACE7GETCLIPPERMETHODVALUE;

typedef struct DirectDrawSurface7GetColorKeyMethodValue
{
    DWORD Options;
    LPDDCOLORKEY ColorKey;
} DIRECTDRAWSURFACE7GETCOLORKEYMETHODVALUE, * LPDIRECTDRAWSURFACE7GETCOLORKEYMETHODVALUE;

typedef struct DirectDrawSurface7GetDCMethodValue
{
    HDC* DC;
} DIRECTDRAWSURFACE7GETDCMETHODVALUE, * LPDIRECTDRAWSURFACE7GETDCMETHODVALUE;

typedef struct DirectDrawSurface7GetFlipStatusMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE7GETFLIPSTATUSMETHODVALUE, * LPDIRECTDRAWSURFACE7GETFLIPSTATUSMETHODVALUE;

typedef struct DirectDrawSurface7GetOverlayPositionMethodValue
{
    LPLONG X;
    LPLONG Y;
} DIRECTDRAWSURFACE7GETOVERLAYPOSITIONMETHODVALUE, * LPDIRECTDRAWSURFACE7GETOVERLAYPOSITIONMETHODVALUE;

typedef struct DirectDrawSurface7GetPaletteMethodValue
{
    LPDIRECTDRAWPALETTE* Palette;
} DIRECTDRAWSURFACE7GETPALETTEMETHODVALUE, * LPDIRECTDRAWSURFACE7GETPALETTEMETHODVALUE;

typedef struct DirectDrawSurface7GetPixelFormatMethodValue
{
    LPDDPIXELFORMAT Format;
} DIRECTDRAWSURFACE7GETPIXELFORMATMETHODVALUE, * LPDIRECTDRAWSURFACE7GETPIXELFORMATMETHODVALUE;

typedef struct DirectDrawSurface7GetSurfaceDescMethodValue
{
    LPDDSURFACEDESC2 Descriptor;
} DIRECTDRAWSURFACE7GETSURFACEDESCMETHODVALUE, * LPDIRECTDRAWSURFACE7GETSURFACEDESCMETHODVALUE;

typedef struct DirectDrawSurface7InitializeMethodValue
{
    LPDIRECTDRAW Object;
    LPDDSURFACEDESC2 Descriptor;
} DIRECTDRAWSURFACE7INITIALIZEMETHODVALUE, * LPDIRECTDRAWSURFACE7INITIALIZEMETHODVALUE;

typedef struct DirectDrawSurface7IsLostMethodValue
{

} DIRECTDRAWSURFACE7ISLOSTMETHODVALUE, * LPDIRECTDRAWSURFACE7ISLOSTMETHODVALUE;

typedef struct DirectDrawSurface7LockMethodValue
{
    LPRECT Rect;
    LPDDSURFACEDESC2 Descriptor;
    DWORD Options;
    HANDLE Event;
} DIRECTDRAWSURFACE7LOCKMETHODVALUE, * LPDIRECTDRAWSURFACE7LOCKMETHODVALUE;

typedef struct DirectDrawSurface7ReleaseDCMethodValue
{
    HDC DC;
} DIRECTDRAWSURFACE7RELEASEDCMETHODVALUE, * LPDIRECTDRAWSURFACE7RELEASEDCMETHODVALUE;

typedef struct DirectDrawSurface7RestoreMethodValue
{

} DIRECTDRAWSURFACE7RESTOREMETHODVALUE, * LPDIRECTDRAWSURFACE7RESTOREMETHODVALUE;

typedef struct DirectDrawSurface7SetClipperMethodValue
{
    LPDIRECTDRAWCLIPPER Clipper;
} DIRECTDRAWSURFACE7SETCLIPPERMETHODVALUE, * LPDIRECTDRAWSURFACE7SETCLIPPERMETHODVALUE;

typedef struct DirectDrawSurface7SetColorKeyMethodValue
{
    DWORD Options;
    LPDDCOLORKEY ColorKey;
} DIRECTDRAWSURFACE7SETCOLORKEYMETHODVALUE, * LPDIRECTDRAWSURFACE7SETCOLORKEYMETHODVALUE;

typedef struct DirectDrawSurface7SetOverlayPositionMethodValue
{
    LONG X;
    LONG Y;
} DIRECTDRAWSURFACE7SETOVERLAYPOSITIONMETHODVALUE, * LPDIRECTDRAWSURFACE7SETOVERLAYPOSITIONMETHODVALUE;

typedef struct DirectDrawSurface7SetPaletteMethodValue
{
    LPDIRECTDRAWPALETTE Palette;
} DIRECTDRAWSURFACE7SETPALETTEMETHODVALUE, * LPDIRECTDRAWSURFACE7SETPALETTEMETHODVALUE;

typedef struct DirectDrawSurface7UnlockMethodValue
{
    LPVOID Value;
} DIRECTDRAWSURFACE7UNLOCKMETHODVALUE, * LPDIRECTDRAWSURFACE7UNLOCKMETHODVALUE;

typedef struct DirectDrawSurface7UpdateOverlayMethodValue
{
    LPRECT Source;
    LPDIRECTDRAWSURFACE7 Surface;
    LPRECT Destination;
    DWORD Options;
    LPDDOVERLAYFX Effect;
} DIRECTDRAWSURFACE7UPDATEOVERLAYMETHODVALUE, * LPDIRECTDRAWSURFACE7UPDATEOVERLAYMETHODVALUE;

typedef struct DirectDrawSurface7UpdateOverlayDisplayMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE7UPDATEOVERLAYDISPLAYMETHODVALUE, * LPDIRECTDRAWSURFACE7UPDATEOVERLAYDISPLAYMETHODVALUE;

typedef struct DirectDrawSurface7UpdateOverlayZOrderMethodValue
{
    DWORD Options;
    LPDIRECTDRAWSURFACE7 Surface;
} DIRECTDRAWSURFACE7UPDATEOVERLAYZORDERMETHODVALUE, * LPDIRECTDRAWSURFACE7UPDATEOVERLAYZORDERMETHODVALUE;

typedef struct DirectDrawSurface7GetDDInterfaceMethodValue
{
    LPVOID* Object;
} DIRECTDRAWSURFACE7GETDDINTERFACEMETHODVALUE, * LPDIRECTDRAWSURFACE7GETDDINTERFACEMETHODVALUE;

typedef struct DirectDrawSurface7PageLockMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE7PAGELOCKMETHODVALUE, * LPDIRECTDRAWSURFACE7PAGELOCKMETHODVALUE;

typedef struct DirectDrawSurface7PageUnlockMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE7PAGEUNLOCKMETHODVALUE, * LPDIRECTDRAWSURFACE7PAGEUNLOCKMETHODVALUE;

typedef struct DirectDrawSurface7SetSurfaceDescMethodValue
{
    LPDDSURFACEDESC2 Descriptor;
    DWORD Options;
} DIRECTDRAWSURFACE7SETSURFACEDESCMETHODVALUE, * LPDIRECTDRAWSURFACE7SETSURFACEDESCMETHODVALUE;

typedef struct DirectDrawSurface7SetPrivateDataMethodValue
{
    GUID ID;
    LPVOID Value;
    DWORD Size;
    DWORD Options;
} DIRECTDRAWSURFACE7SETPRIVATEDATAMETHODVALUE, * LPDIRECTDRAWSURFACE7SETPRIVATEDATAMETHODVALUE;

typedef struct DirectDrawSurface7GetPrivateDataMethodValue
{
    GUID ID;
    LPVOID Value;
    LPDWORD Size;
} DIRECTDRAWSURFACE7GETPRIVATEDATAMETHODVALUE, * LPDIRECTDRAWSURFACE7GETPRIVATEDATAMETHODVALUE;

typedef struct DirectDrawSurface7FreePrivateDataMethodValue
{
    GUID ID;
} DIRECTDRAWSURFACE7FREEPRIVATEDATAMETHODVALUE, * LPDIRECTDRAWSURFACE7FREEPRIVATEDATAMETHODVALUE;

typedef struct DirectDrawSurface7GetUniquenessValueMethodValue
{
    LPDWORD Value;
} DIRECTDRAWSURFACE7GETUNIQUENESSVALUEMETHODVALUE, * LPDIRECTDRAWSURFACE7GETUNIQUENESSVALUEMETHODVALUE;

typedef struct DirectDrawSurface7ChangeUniquenessValueMethodValue
{

} DIRECTDRAWSURFACE7CHANGEUNIQUENESSVALUEMETHODVALUE, * LPDIRECTDRAWSURFACE7CHANGEUNIQUENESSVALUEMETHODVALUE;

typedef struct DirectDrawSurface7SetPriorityMethodValue
{
    DWORD Priority;
} DIRECTDRAWSURFACE7SETPRIORITYMETHODVALUE, * LPDIRECTDRAWSURFACE7SETPRIORITYMETHODVALUE;

typedef struct DirectDrawSurface7GetPriorityMethodValue
{
    LPDWORD Priority;
} DIRECTDRAWSURFACE7GETPRIORITYMETHODVALUE, * LPDIRECTDRAWSURFACE7GETPRIORITYMETHODVALUE;

typedef struct DirectDrawSurface7SetLODMethodValue
{
    DWORD Value;
} DIRECTDRAWSURFACE7SETLODMETHODVALUE, * LPDIRECTDRAWSURFACE7SETLODMETHODVALUE;

typedef struct DirectDrawSurface7GetLODMethodValue
{
    LPDWORD Value;
} DIRECTDRAWSURFACE7GETLODMETHODVALUE, * LPDIRECTDRAWSURFACE7GETLODMETHODVALUE;

typedef struct DirectDrawSurface7EnumAttachedSurfacesMethodCallbackValue
{
    LPVOID Object;
    LPDIRECTDRAWSURFACE7 Surface;
    LPDDSURFACEDESC2 Descriptor;
} DIRECTDRAWSURFACE7ENUMATTACHEDSURFACESMETHODCALLBACKVALUE, * LPDIRECTDRAWSURFACE7ENUMATTACHEDSURFACESMETHODCALLBACKVALUE;

typedef struct DirectDrawSurface7EnumOverlayZOrdersMethodCallbackValue
{
    LPVOID Object;
    LPDIRECTDRAWSURFACE7 Surface;
    LPDDSURFACEDESC2 Descriptor;
} DIRECTDRAWSURFACE7ENUMOVERLAYZORDERSMETHODCALLBACKVALUE, * LPDIRECTDRAWSURFACE7ENUMOVERLAYZORDERSMETHODCALLBACKVALUE;