/*
Copyright (c) 2024 Eugene Kirian

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "Base.hxx"

typedef struct DirectDrawSurface2QueryInterfaceMethodValue
{
    GUID ID;
    LPVOID* Object;
} DIRECTDRAWSURFACE2QUERYINTERFACEMETHODVALUE, * LPDIRECTDRAWSURFACE2QUERYINTERFACEMETHODVALUE;

typedef struct DirectDrawSurface2AddRefMethodValue
{

} DIRECTDRAWSURFACE2ADDREFMETHODVALUE, * LPDIRECTDRAWSURFACE2ADDREFMETHODVALUE;

typedef struct DirectDrawSurface2ReleaseMethodValue
{

} DIRECTDRAWSURFACE2RELEASEMETHODVALUE, * LPDIRECTDRAWSURFACE2RELEASEMETHODVALUE;

typedef struct DirectDrawSurface2AddAttachedSurfaceMethodValue
{
    LPDIRECTDRAWSURFACE2 Surface;
} DIRECTDRAWSURFACE2ADDATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACE2ADDATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurface2AddOverlayDirtyRectMethodValue
{
    LPRECT Rect;
} DIRECTDRAWSURFACE2ADDOVERLAYDIRTYRECTMETHODVALUE, * LPDIRECTDRAWSURFACE2ADDOVERLAYDIRTYRECTMETHODVALUE;

typedef struct DirectDrawSurface2BltMethodValue
{
    LPRECT Destination;
    LPDIRECTDRAWSURFACE2 Surface;
    LPRECT Source;
    DWORD Options;
    LPDDBLTFX Effect;
} DIRECTDRAWSURFACE2BLTMETHODVALUE, * LPDIRECTDRAWSURFACE2BLTMETHODVALUE;

typedef struct DirectDrawSurface2BltBatchMethodValue
{
    LPDDBLTBATCH Batch;
    DWORD Count;
    DWORD Options;
} DIRECTDRAWSURFACE2BLTBATCHMETHODVALUE, * LPDIRECTDRAWSURFACE2BLTBATCHMETHODVALUE;

typedef struct DirectDrawSurface2BltFastMethodValue
{
    DWORD X;
    DWORD Y;
    LPDIRECTDRAWSURFACE2 Surface;
    LPRECT Rect;
    DWORD Transparent;
} DIRECTDRAWSURFACE2BLTFASTMETHODVALUE, * LPDIRECTDRAWSURFACE2BLTFASTMETHODVALUE;

typedef struct DirectDrawSurface2DeleteAttachedSurfaceMethodValue
{
    DWORD Options;
    LPDIRECTDRAWSURFACE2 Surface;
} DIRECTDRAWSURFACE2DELETEATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACE2DELETEATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurface2EnumAttachedSurfacesMethodValue
{
    LPVOID Context;
    LPDDENUMSURFACESCALLBACK EnumSurfacesCallback;
} DIRECTDRAWSURFACE2ENUMATTACHEDSURFACESMETHODVALUE, * LPDIRECTDRAWSURFACE2ENUMATTACHEDSURFACESMETHODVALUE;

typedef struct DirectDrawSurface2EnumOverlayZOrdersMethodValue
{
    DWORD Options;
    LPVOID Context;
    LPDDENUMSURFACESCALLBACK Callback;
} DIRECTDRAWSURFACE2ENUMOVERLAYZORDERSMETHODVALUE, * LPDIRECTDRAWSURFACE2ENUMOVERLAYZORDERSMETHODVALUE;

typedef struct DirectDrawSurface2FlipMethodValue
{
    LPDIRECTDRAWSURFACE2 Surface;
    DWORD Options;
} DIRECTDRAWSURFACE2FLIPMETHODVALUE, * LPDIRECTDRAWSURFACE2FLIPMETHODVALUE;

typedef struct DirectDrawSurface2GetAttachedSurfaceMethodValue
{
    LPDDSCAPS Caps;
    LPDIRECTDRAWSURFACE2* Surface;
} DIRECTDRAWSURFACE2GETATTACHEDSURFACEMETHODVALUE, * LPDIRECTDRAWSURFACE2GETATTACHEDSURFACEMETHODVALUE;

typedef struct DirectDrawSurface2GetBltStatusMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE2GETBLTSTATUSMETHODVALUE, * LPDIRECTDRAWSURFACE2GETBLTSTATUSMETHODVALUE;

typedef struct DirectDrawSurface2GetCapsMethodValue
{
    LPDDSCAPS Caps;
} DIRECTDRAWSURFACE2GETCAPSMETHODVALUE, * LPDIRECTDRAWSURFACE2GETCAPSMETHODVALUE;

typedef struct DirectDrawSurface2GetClipperMethodValue
{
    LPDIRECTDRAWCLIPPER* Clipper;
} DIRECTDRAWSURFACE2GETCLIPPERMETHODVALUE, * LPDIRECTDRAWSURFACE2GETCLIPPERMETHODVALUE;

typedef struct DirectDrawSurface2GetColorKeyMethodValue
{
    DWORD Options;
    LPDDCOLORKEY ColorKey;
} DIRECTDRAWSURFACE2GETCOLORKEYMETHODVALUE, * LPDIRECTDRAWSURFACE2GETCOLORKEYMETHODVALUE;

typedef struct DirectDrawSurface2GetDCMethodValue
{
    HDC* DC;
} DIRECTDRAWSURFACE2GETDCMETHODVALUE, * LPDIRECTDRAWSURFACE2GETDCMETHODVALUE;

typedef struct DirectDrawSurface2GetFlipStatusMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE2GETFLIPSTATUSMETHODVALUE, * LPDIRECTDRAWSURFACE2GETFLIPSTATUSMETHODVALUE;

typedef struct DirectDrawSurface2GetOverlayPositionMethodValue
{
    LPLONG X;
    LPLONG Y;
} DIRECTDRAWSURFACE2GETOVERLAYPOSITIONMETHODVALUE, * LPDIRECTDRAWSURFACE2GETOVERLAYPOSITIONMETHODVALUE;

typedef struct DirectDrawSurface2GetPaletteMethodValue
{
    LPDIRECTDRAWPALETTE* Palette;
} DIRECTDRAWSURFACE2GETPALETTEMETHODVALUE, * LPDIRECTDRAWSURFACE2GETPALETTEMETHODVALUE;

typedef struct DirectDrawSurface2GetPixelFormatMethodValue
{
    LPDDPIXELFORMAT Format;
} DIRECTDRAWSURFACE2GETPIXELFORMATMETHODVALUE, * LPDIRECTDRAWSURFACE2GETPIXELFORMATMETHODVALUE;

typedef struct DirectDrawSurface2GetSurfaceDescMethodValue
{
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACE2GETSURFACEDESCMETHODVALUE, * LPDIRECTDRAWSURFACE2GETSURFACEDESCMETHODVALUE;

typedef struct DirectDrawSurface2InitializeMethodValue
{
    LPDIRECTDRAW Object;
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACE2INITIALIZEMETHODVALUE, * LPDIRECTDRAWSURFACE2INITIALIZEMETHODVALUE;

typedef struct DirectDrawSurface2IsLostMethodValue
{

} DIRECTDRAWSURFACE2ISLOSTMETHODVALUE, * LPDIRECTDRAWSURFACE2ISLOSTMETHODVALUE;

typedef struct DirectDrawSurface2LockMethodValue
{
    LPRECT Rect;
    LPDDSURFACEDESC Descriptor;
    DWORD Options;
    HANDLE Event;
} DIRECTDRAWSURFACE2LOCKMETHODVALUE, * LPDIRECTDRAWSURFACE2LOCKMETHODVALUE;

typedef struct DirectDrawSurface2ReleaseDCMethodValue
{
    HDC DC;
} DIRECTDRAWSURFACE2RELEASEDCMETHODVALUE, * LPDIRECTDRAWSURFACE2RELEASEDCMETHODVALUE;

typedef struct DirectDrawSurface2RestoreMethodValue
{

} DIRECTDRAWSURFACE2RESTOREMETHODVALUE, * LPDIRECTDRAWSURFACE2RESTOREMETHODVALUE;

typedef struct DirectDrawSurface2SetClipperMethodValue
{
    LPDIRECTDRAWCLIPPER Clipper;
} DIRECTDRAWSURFACE2SETCLIPPERMETHODVALUE, * LPDIRECTDRAWSURFACE2SETCLIPPERMETHODVALUE;

typedef struct DirectDrawSurface2SetColorKeyMethodValue
{
    DWORD Options;
    LPDDCOLORKEY ColorKey;
} DIRECTDRAWSURFACE2SETCOLORKEYMETHODVALUE, * LPDIRECTDRAWSURFACE2SETCOLORKEYMETHODVALUE;

typedef struct DirectDrawSurface2SetOverlayPositionMethodValue
{
    LONG X;
    LONG Y;
} DIRECTDRAWSURFACE2SETOVERLAYPOSITIONMETHODVALUE, * LPDIRECTDRAWSURFACE2SETOVERLAYPOSITIONMETHODVALUE;

typedef struct DirectDrawSurface2SetPaletteMethodValue
{
    LPDIRECTDRAWPALETTE Palette;
} DIRECTDRAWSURFACE2SETPALETTEMETHODVALUE, * LPDIRECTDRAWSURFACE2SETPALETTEMETHODVALUE;

typedef struct DirectDrawSurface2UnlockMethodValue
{
    LPVOID Value;
} DIRECTDRAWSURFACE2UNLOCKMETHODVALUE, * LPDIRECTDRAWSURFACE2UNLOCKMETHODVALUE;

typedef struct DirectDrawSurface2UpdateOverlayMethodValue
{
    LPRECT Source;
    LPDIRECTDRAWSURFACE2 Surface;
    LPRECT Destination;
    DWORD Options;
    LPDDOVERLAYFX Effect;
} DIRECTDRAWSURFACE2UPDATEOVERLAYMETHODVALUE, * LPDIRECTDRAWSURFACE2UPDATEOVERLAYMETHODVALUE;

typedef struct DirectDrawSurface2UpdateOverlayDisplayMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE2UPDATEOVERLAYDISPLAYMETHODVALUE, * LPDIRECTDRAWSURFACE2UPDATEOVERLAYDISPLAYMETHODVALUE;

typedef struct DirectDrawSurface2UpdateOverlayZOrderMethodValue
{
    DWORD Options;
    LPDIRECTDRAWSURFACE2 Surface;
} DIRECTDRAWSURFACE2UPDATEOVERLAYZORDERMETHODVALUE, * LPDIRECTDRAWSURFACE2UPDATEOVERLAYZORDERMETHODVALUE;

typedef struct DirectDrawSurface2GetDDInterfaceMethodValue
{
    LPVOID* Object;
} DIRECTDRAWSURFACE2GETDDINTERFACEMETHODVALUE, * LPDIRECTDRAWSURFACE2GETDDINTERFACEMETHODVALUE;

typedef struct DirectDrawSurface2PageLockMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE2PAGELOCKMETHODVALUE, * LPDIRECTDRAWSURFACE2PAGELOCKMETHODVALUE;

typedef struct DirectDrawSurface2PageUnlockMethodValue
{
    DWORD Options;
} DIRECTDRAWSURFACE2PAGEUNLOCKMETHODVALUE, * LPDIRECTDRAWSURFACE2PAGEUNLOCKMETHODVALUE;

typedef struct DirectDrawSurface2EnumAttachedSurfacesMethodCallbackValue
{
    LPVOID Object;
    LPDIRECTDRAWSURFACE Surface;
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACE2ENUMATTACHEDSURFACESMETHODCALLBACKVALUE, * LPDIRECTDRAWSURFACE2ENUMATTACHEDSURFACESMETHODCALLBACKVALUE;

typedef struct DirectDrawSurface2EnumOverlayZOrdersMethodCallbackValue
{
    LPVOID Object;
    LPDIRECTDRAWSURFACE Surface;
    LPDDSURFACEDESC Descriptor;
} DIRECTDRAWSURFACE2ENUMOVERLAYZORDERSMETHODCALLBACKVALUE, * LPDIRECTDRAWSURFACE2ENUMOVERLAYZORDERSMETHODCALLBACKVALUE;